# Generated by Django 5.1.2 on 2025-03-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
