services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: djangodb

  ddd_app_server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./ddd_app_server:/app
      - static_volume:/tmp/static
      - media_volume:/tmp/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - 443:443
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      # - ./config/nginx/conf.d/ddd-app-server.conf:/etc/nginx/conf.d/ddd-app-server.conf
      # - ./config/nginx/conf.d/ddd-app-server-dev.conf:/etc/nginx/conf.d/ddd-app-server-dev.conf
      - static_volume:/tmp/static
      - media_volume:/tmp/media
    # depends_on:
    #   - ddd_app_server

volumes:
  static_volume:
  media_volume:
  postgres_data:
