# Generated by Django 5.1.2 on 2025-04-03 08:34

import django.db.models.deletion
import invites.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "invite_type",
                    models.CharField(
                        choices=[("member", "멤버"), ("moderator", "운영진")], max_length=10
                    ),
                ),
                ("used", models.BooleanField(default=False)),
                (
                    "expire_time",
                    models.DateTimeField(default=invites.models.one_week_from_now),
                ),
                ("one_time_use", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invite_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
