# Generated by Django 5.1.2 on 2025-05-06 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schedules', '0002_attendance_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, related_name='assigned_schedules', to='auth.group'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
