# Generated by Django 5.1.2 on 2025-05-12 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schedules', '0003_remove_attendance_attendance_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['start_time', 'title']},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='assigned_groups',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(default=24, help_text='The group to which this schedule is assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='auth.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the schedule was created.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the schedule.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(help_text='The date and time when the schedule ends.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the schedule.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(help_text='The date and time when the schedule starts.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(help_text='The title of the schedule.', max_length=200),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
