# Generated by Django 5.1.2 on 2025-05-16 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0002_cohort_profile_cohort'),
        ('schedules', '0004_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='profiles.cohort'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(help_text='The group to which this schedule is assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='auth.group'),
        ),
    ]
