# Generated by Django 5.1.2 on 2025-08-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_schedule_cohort_alter_schedule_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='cohort',
        ),
    ]
