# Generated by Django 5.1.2 on 2025-05-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_cohort_profile_cohort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cohort',
            new_name='cohort_id',
        ),
    ]
