# Generated by Django 5.1.2 on 2025-05-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_cohort_profile_cohort_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cohort_id',
        ),
    ]
