# Generated by Django 5.1.2 on 2025-08-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0004_remove_attendance_cohort'),
        ('profiles', '0004_remove_profile_cohort_id'),
        ('schedules', '0006_remove_schedule_cohort'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cohort',
        ),
    ]
