# Generated by Django 5.1.2 on 2025-05-16 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
        ('profiles', '0002_cohort_profile_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='profiles.cohort'),
        ),
    ]
