# Generated by Django 5.1.2 on 2025-05-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_attendance_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('tbd', '미정'), ('present', '출석'), ('late', '지각'), ('absent', '결석'), ('exception', '예외'), ('auto', '자동')], default='tbd', max_length=10),
        ),
    ]
