# Generated by Django 5.1.2 on 2025-08-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='cohort',
        ),
    ]
